pages:
  script:
  - mkdir .public
  - git submodule update --init -- docs
  - pip install -U sphinx
  - cd docs && make html
  - cp -r docs/_build/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
