trainer: generic
output_dir: $BENCHMARK_RESULTS_PATH/multiclass

data_config:
    batch_size: 128
    sample_size: 1
    img_size: 200
    num_labels: 2
    data_path: /Users/vadumont/Desktop/
    use_dist_sampler_train: true
    use_dist_sampler_valid: false
    from_dict: false

model_config:
    model_type: resnet
    num_classes: 2
    depth: 2
    learning_rate: 0.01
    momentum: 0.9
    optimizer: 'SGD'
    loss: 'CE'

train_config:
    n_epochs: 1
