trainer: generic
output_dir: /Users/vadumont/Desktop

data_config:
  name: 'fwi'
  batch_size: 8
  data_path: /Users/vadumont/Desktop/FWI/data
  input_type: 'field'
  refine: 50
  conv2d: 2
  norm: True

model_config:
  #model_type: resnet
  #depth: 8
  #num_classes: 12
  model_type: mlp
  n_layer:
    - 37500
    - 5000
    - 1000
    - 100
  learning_rate: 0.01
  momentum: 0.9
  optimizer: 'SGD'
  loss: 'MSE'
  
train_config:
  n_epochs: 20
  acc_tol: 0.01
  rounded: False
